In [35]:
import geopandas  as gpd
import pandas as pd

In [36]:
focos_csv = gpd.read_file('bdqueimadas_2024-08-04_2024-09-04.csv')

In [37]:
focos_csv.head()

,DataHora,Satelite,Pais,Estado,Municipio,Bioma,DiaSemChuva,Precipitacao,RiscoFogo,FRP,Latitude,Longitude
0,2024/08/04 00:06:40,GOES-16,Brasil,MATO GROSSO,BARÃO DE MELGAÇO,Pantanal,3,0.0,1.0,70.1,-16.6865,-56.2636
1,2024/08/04 00:06:40,GOES-16,Brasil,MATO GROSSO,BARÃO DE MELGAÇO,Pantanal,5,0.0,1.0,146.9,-16.6868,-56.243
2,2024/08/04 00:06:40,GOES-16,Brasil,MATO GROSSO,BARÃO DE MELGAÇO,Pantanal,2,0.0,1.0,140.1,-16.7061,-56.2612
3,2024/08/04 00:06:40,GOES-16,Brasil,MATO GROSSO,BARÃO DE MELGAÇO,Pantanal,7,0.0,1.0,182.4,-16.7064,-56.2406
4,2024/08/04 00:06:41,GOES-16,Brasil,MATO GROSSO,BARÃO DE MELGAÇO,Pantanal,8,0.0,1.0,77.7,-16.726,-56.2382

In [38]:
focos_csv.drop(columns=['Bioma', 'Precipitacao', 'DiaSemChuva', 'RiscoFogo', 'FRP', 'Estado', 'Pais', 'Municipio'], inplace=True)

/tmp/ipykernel_1400167/998667899.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  focos_csv.drop(columns=['Bioma', 'Precipitacao', 'DiaSemChuva', 'RiscoFogo', 'FRP', 'Estado', 'Pais', 'Municipio'], inplace=True)

In [39]:
geometry = gpd.points_from_xy(focos_csv['Longitude'], focos_csv['Latitude'])
gdf = gpd.GeoDataFrame(focos_csv, geometry=geometry, crs='EPSG:4326')

In [40]:
gdf['id_foco'] = gdf.index

In [41]:
gdf.rename(columns={'id_foco': 'id','DataHora':'data', 'Satelite': 'satelite'}, inplace=True)

/tmp/ipykernel_1400167/484641748.py:1: Pandas4Warning: The inplace keyword in GeoDataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  gdf.rename(columns={'id_foco': 'id','DataHora':'data', 'Satelite': 'satelite'}, inplace=True)

In [42]:
if not pd.api.types.is_datetime64_any_dtype(gdf["data"]):
        gdf["data"] = pd.to_datetime(gdf["data"])

In [43]:
gdf.drop(columns=['Latitude', 'Longitude'], inplace=True)

/tmp/ipykernel_1400167/3475909317.py:1: Pandas4Warning: The inplace keyword in GeoDataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  gdf.drop(columns=['Latitude', 'Longitude'], inplace=True)

In [44]:
gdf

                     data satelite                   geometry     id
0     2024-08-04 00:06:40  GOES-16  POINT (-56.2636 -16.6865)      0
1     2024-08-04 00:06:40  GOES-16   POINT (-56.243 -16.6868)      1
2     2024-08-04 00:06:40  GOES-16  POINT (-56.2612 -16.7061)      2
3     2024-08-04 00:06:40  GOES-16  POINT (-56.2406 -16.7064)      3
4     2024-08-04 00:06:41  GOES-16   POINT (-56.2382 -16.726)      4
...                   ...      ...                        ...    ...
31865 2024-09-04 23:56:40  GOES-16  POINT (-55.3735 -16.6819)  31865
31866 2024-09-04 23:56:40  GOES-16  POINT (-55.3527 -16.6822)  31866
31867 2024-09-04 23:56:40  GOES-16   POINT (-55.371 -16.7015)  31867
31868 2024-09-04 23:56:40  GOES-16  POINT (-55.3502 -16.7018)  31868
31869 2024-09-04 23:56:49  GOES-16  POINT (-57.4903 -18.4367)  31869

[31870 rows x 4 columns]

In [45]:
gdf.to_file('focosPantanal040824040924.geojson', driver='GEOJSON')